version: "3"
services:
  api:
    build: ./api
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 4000 -b '0.0.0.0'"
    volumes:
      - ./api:/app
    ports:
      - "4000:4000"
    stdin_open: true
    tty: true
  client:
    build: ./client
    command: yarn start
    volumes:
      - ./client:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - api
